# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install all dependencies (including dev) and build
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app

# Install only production dependencies, skip scripts
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Copy built application
COPY --from=builder /app/build ./build

# Default command: run the MCP server
CMD ["node", "build/index.js"]
